### ISSUE TITLE
left-to-right

### ISSUE THREAD

**Issue by mostafaac30** [Shoryu-Y/turn_page_transition#3]
how can I make the transition left to right?
 instead right to the left

**Comment by Shoryu-Y** [comment]
Hi @mostafaac30.
Thank you for making the issue!

I thought transition left to right was necessary too. But I had not yet implemented it.

It will be added in the next version.
Please wait a moment!

**Comment by Shoryu-Y** [comment]
Hi! Dear @mostafaac30 .
turn_page_transition has been released version 0.2.0 and it allows left-to-right turns.

I hope this package will help you.

**Comment by mostafaac30** [comment]
That's the best,
It helped me too much.
Thanks @Shoryu-Y
